name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          ref: 'master'
      - name: Use Node.js v16 (LTS)
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - run: |
          yarn build
          yarn build:types
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
