name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: 'main'

      - name: Use Node.js v18 (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: |
          yarn build
          yarn build:types

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
